export default {
    AUCTION: {
        CREATE: 'CREATE_AUCTION',
        UPDATE: 'UPDATE_AUCTION',
        GET_BY_ID: 'GET_AUCTION_BY_ID',
        GET_LIST: 'GET_AUCTION_LIST',
        REGISTER: 'REGISTER_AUCTION',
        GET_ACTIVITIES: 'GET_AUCTION_ACTIVITY_LIST',
        GET_BIDDERS: 'GET_AUCTION_BIDDER_LIST',
        VERIFY_BIDDER: 'VERIFY_BIDDER_PARTICIPATION',
        JOIN_SESSION: 'JOIN_AUCTION_SESSION',
        GET_PARTICIPATION_STATUS: 'GET_PARTICIPATION_STATUS'
    },
    ASSET: {
        CREATE: 'CREATE_ASSET',
        UPDATE: 'UPDATE_ASSET',
        GET_BY_ID: 'GET_ASSET_BY_ID',
        GET_LIST: 'GET_ASSET_LIST',
        VERIFY: 'VERIFY_ASSET'
    }
};
